name: Test MyCLI Setup

on:
  push:
    branches:
      - main
      - create-custom-cli-action

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MyCLI
        uses: ./.github/actions/my-cli-action
        with:
          version: '1.2.3'

      - name: Verify CLI Installation
        run: |
          echo "Checking MyCLI version..."
          mycli --version

      - name: Cache MyCLI
        if: success()
        uses: actions/cache@v4
        with:
          path: ~/.mycli
          key: mycli-${{ runner.os }}-${{ inputs.version }}    