name: Using Custom Acion
on:
  push:
    branches: [ "main" ] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use my Custom Composite action
        uses: ./actions/my-composite-action
        with:
          node-version: '18'
