
name: Using Custom Acion
on:
   [push]
branch:
  main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: ../.github/actions/my-composite-action
        with:
          node-version: '18'
